version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.4.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: keshabmanni/demo-action-server:v1.0_a
    expose: 5055