name: Continuous Integration
on:
  push:
    branches:
      - main
    # paths:
    # - 'actions/**'
    # - '.github/workflows/**'
    # - 'Dockerfile'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Rasa Server image
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: rasa_server
      name: Build an rasa server
      uses: mr-smithers-excellent/docker-build-push@v5
      # Full list of parameters: https://github.com/RasaHQ/action-server-gha/tree/master#input-arguments
      with:
        dockerfile: ./Dockerfile
        image: 'keshabmanni/demo-rasa-server'
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        tags: 'v1.1'
